# Import Packages
library(igraph)
# Import the CSV Dataset
dataset <- read.csv("USPresidency.csv")

calc_hamming <- function(matrix){
    hamming_distance_matrix <- matrix(0, nrow = 12, ncol = 12)
    for(i in 1:12){
        for(j in 1:12){
        hamming_distance_matrix[i,j] <- sum(matrix[i] != matrix[j])
        }
    }
    return(hamming_distance_matrix)
}
calc_jaccard <- function(matrix){
    jaccard_measure_matrix <- matrix(0, nrow = 12, ncol = 12)
    for(i in 1:12){
        for(j in 1:12){
        jaccard_measure_matrix[i,j] <- sum(matrix[i] != matrix[j])/sum(matrix[i] | matrix[j])
        }
    }
    return(jaccard_measure_matrix)
}
# Task 1)a): Hamming distance matrix between app pairs of elections (for all elections)
print("TASK 1)A)")
calc_hamming(dataset_matrix)
#Task 1)a) the matrix generated by the Jaccard measure.
calc_jaccard(dataset_matrix)

#Task 1)b) the Minimum Spanning Tree having as input that distance matrix. Visualize the result using the yEd software.
print("TASK 1)C)")
#Convert data to graph object
mst(hamming_distance_matrix)
